### ISSUE TITLE
Plugin not working on Linux

### ISSUE THREAD

**Issue by Xenonus** [l-Nuril-l/Voice-Messages-Plugin-BetterDiscord#4]
I did everything as in the instruction, but when I record a message it sends 0 sec file.
Operating system: Ubuntu 20.04

**Comment by l-Nuril-l** [comment]
What is the error in the console?

**Comment by Xenonus** [comment]
Entire log: 
[discord.com-1658434633397.log](https://github.com/l-Nuril-l/Voice-Messages-Plugin-BetterDiscord/files/9162523/discord.com-1658434633397.log)
What happens when I click record: 
![Screenshot from 2022-07-21 22-13-12](https://user-images.githubusercontent.com/90400636/180307704-7e7893eb-f3c8-4ba4-b3aa-fc7f9cfdeb2c.png)

I don't know if it will help.

**Comment by Xenonus** [comment]
.

**Comment by l-Nuril-l** [comment]
I can't figure out what the problem is based on this error.
Besides, I don't use Linux and I can't check 😕 (The manual for it was left from the previous developer https://github.com/p0rtL6/BetterDiscord-Plugins/tree/main/Voice%20Messages)

**Comment by YourSandwich** [comment]
This is the error log.
```
Error: ENOENT: no such file or directory, lstat '/usr/bin/child_process'
    at Object.realpathSync (betterdiscord/renderer.js:5:331452)
    at p.getFilePath (betterdiscord/renderer.js:5:333151)
    at p._load (betterdiscord/renderer.js:5:333246)
    at betterdiscord/renderer.js:5:336308
    at plugin (betterdiscord://plugins/VoiceMessages.plugin.js:113:29)
    at eval (betterdiscord://plugins/VoiceMessages.plugin.js:523:20)
    at eval (betterdiscord://plugins/VoiceMessages.plugin.js:524:11)
    at eval (betterdiscord://plugins/VoiceMessages.plugin.js:525:3)
    at A.requireAddon (betterdiscord/renderer.js:5:34905)
    at A.loadAddon (betterdiscord/renderer.js:5:7343)
    at A.loadAddon (betterdiscord/renderer.js:5:32573)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:5:5323)
```

**Comment by l-Nuril-l** [comment]
The plugin is no longer platform dependent.
